name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Uncomment and use this if you're using environment secrets instead of repository secrets
    # environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm i
        
      - name: Build project
        run: npm run build
        
      - name: Create zip file
        run: |
          cd out
          zip -r ../out.zip .
          cd ..
          
      - name: Upload build using SCP (SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CPANEL_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 22
          source: "out.zip"
          target: ${{ secrets.CPANEL_PATH }}
            
      - name: Extract zip file on cPanel
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CPANEL_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          command: |
            cd ${{ secrets.CPANEL_PATH }}
            unzip -o out.zip -d ${{ secrets.EXTRACT_PATH }}
            rm out.zip
